In [1]:
import pandas as pd
import numpy as np

In [3]:
se = pd.Series(['tv',2300,'kt',1980],index=[[1,1,2,2],['prodct','price','product','price']])

In [4]:
se

1  prodct       tv
   price      2300
2  product      kt
   price      1980
dtype: object

In [5]:
from pandas import DataFrame,Series

In [6]:
data = np.array([[2300,1.00],[1980,1.00],[3600,0.96],[2100,0.98]])

In [7]:
data

array([[2.30e+03, 1.00e+00],
       [1.98e+03, 1.00e+00],
       [3.60e+03, 9.60e-01],
       [2.10e+03, 9.80e-01]])

In [10]:
df = DataFrame(data,columns=['价格','折扣率'],index=[['格力','格力','tcl','tcl'],['tv','kt','tv','kt']])

In [11]:
df

价格   折扣率
格力  tv  2300.0  1.00
    kt  1980.0  1.00
tcl tv  3600.0  0.96
    kt  2100.0  0.98

In [13]:
mindex = df.index

In [14]:
mindex

MultiIndex([( '格力', 'tv'),
            ( '格力', 'kt'),
            ('tcl', 'tv'),
            ('tcl', 'kt')],
           )

In [15]:
mindex[0:4]

MultiIndex([( '格力', 'tv'),
            ( '格力', 'kt'),
            ('tcl', 'tv'),
            ('tcl', 'kt')],
           )

In [20]:
type(mindex)

pandas.core.indexes.multi.MultiIndex

In [22]:
%pwd


'/Users/liyian/workspace/VScode_learn'

In [23]:
mindex?

In [24]:
mindex.levels

FrozenList([['tcl', '格力'], ['kt', 'tv']])

In [25]:
mindex.levels[0]

Index(['tcl', '格力'], dtype='object')

In [27]:
mindex.labels[0]

AttributeError: 'MultiIndex' object has no attribute 'labels'

In [37]:
mindex.codes

FrozenList([[1, 1, 0, 0], [1, 0, 1, 0]])

In [38]:
mindex.codes[0]

array([1, 1, 0, 0], dtype=int8)

In [29]:
mindex.get_loc(('格力','tv'))

0

In [30]:
mindex

MultiIndex([( '格力', 'tv'),
            ( '格力', 'kt'),
            ('tcl', 'tv'),
            ('tcl', 'kt')],
           )

In [31]:
mindex[0]

('格力', 'tv')

In [32]:
df

价格   折扣率
格力  tv  2300.0  1.00
    kt  1980.0  1.00
tcl tv  3600.0  0.96
    kt  2100.0  0.98

In [35]:
df.loc

In [40]:
mindex.get_loc(('格力','kt'))

1

In [41]:
mindex.get_indexer([('格力','tv'),('tcl','kt'),'nothing'])

array([ 0,  3, -1])

In [42]:
 df_arrays = DataFrame(
    data,columns=[' 价格 ',' 折扣率 '],
    index=pd.MultiIndex.from_arrays([
        [' 格力 ',' 格力 ','TCL','TCL'], 
        [' 电视机 ',' 空调 ',' 电视机 ',' 空调 ']
    ])
)


In [43]:
df_arrays

价格    折扣率 
 格力   电视机   2300.0   1.00
      空调    1980.0   1.00
TCL   电视机   3600.0   0.96
      空调    2100.0   0.98

In [44]:
se

1  prodct       tv
   price      2300
2  product      kt
   price      1980
dtype: object

In [47]:
se[2,'price']

1980

In [48]:
se[2]

product      kt
price      1980
dtype: object

In [49]:
se[2]['price']

1980

In [51]:
se.iloc[1:3]

1  price      2300
2  product      kt
dtype: object

In [53]:
se.iloc[1]

2300

In [54]:
df

价格   折扣率
格力  tv  2300.0  1.00
    kt  1980.0  1.00
tcl tv  3600.0  0.96
    kt  2100.0  0.98

In [55]:
df['价格']

格力   tv    2300.0
     kt    1980.0
tcl  tv    3600.0
     kt    2100.0
Name: 价格, dtype: float64

In [56]:
df[0:1]

价格  折扣率
格力 tv  2300.0  1.0

In [57]:
df[0:2]['价格']

格力  tv    2300.0
    kt    1980.0
Name: 价格, dtype: float64

In [59]:
df.loc['格力']

价格  折扣率
tv  2300.0  1.0
kt  1980.0  1.0

In [60]:
df.index.names = ['key1','key2']

In [61]:
df

价格   折扣率
key1 key2              
格力   tv    2300.0  1.00
     kt    1980.0  1.00
tcl  tv    3600.0  0.96
     kt    2100.0  0.98

In [66]:
df.swaplevel('key1','key2')

价格   折扣率
key2 key1              
tv   格力    2300.0  1.00
kt   格力    1980.0  1.00
tv   tcl   3600.0  0.96
kt   tcl   2100.0  0.98

In [67]:
df.sort_index(level=1)

价格   折扣率
key1 key2              
tcl  kt    2100.0  0.98
格力   kt    1980.0  1.00
tcl  tv    3600.0  0.96
格力   tv    2300.0  1.00

In [69]:
df

价格   折扣率
key1 key2              
格力   tv    2300.0  1.00
     kt    1980.0  1.00
tcl  tv    3600.0  0.96
     kt    2100.0  0.98

In [78]:
df.sort_index

<bound method DataFrame.sort_index of                价格   折扣率
key1 key2              
格力   tv    2300.0  1.00
     kt    1980.0  1.00
tcl  tv    3600.0  0.96
     kt    2100.0  0.98>

In [76]:
df?

In [79]:
df_arrays.index.names = ['key1','key2']

In [80]:
df_arrays.sort_index(level=1)

价格    折扣率 
key1 key2                
 格力   电视机   2300.0   1.00
TCL   电视机   3600.0   0.96
 格力   空调    1980.0   1.00
TCL   空调    2100.0   0.98

In [81]:
df_arrays.sort_index(level=0)

价格    折扣率 
key1 key2                
 格力   电视机   2300.0   1.00
      空调    1980.0   1.00
TCL   电视机   3600.0   0.96
      空调    2100.0   0.98

In [82]:
df_arrays

价格    折扣率 
key1 key2                
 格力   电视机   2300.0   1.00
      空调    1980.0   1.00
TCL   电视机   3600.0   0.96
      空调    2100.0   0.98

In [83]:
df_arrays.sort_index(level=None)

价格    折扣率 
key1 key2                
 格力   电视机   2300.0   1.00
      空调    1980.0   1.00
TCL   电视机   3600.0   0.96
      空调    2100.0   0.98

In [85]:
unsorted_df = pd.DataFrame(np.random.randn(10,2),index=[1,4,6,2,3,5,9,8,0,7],columns = ['col2','col1'])

In [86]:
unsorted_df

col2      col1
1 -0.727589 -1.869765
4  0.265399 -1.052917
6 -0.674762 -0.354448
2 -1.066839 -0.381800
3 -0.018958 -0.906805
5  1.445366  0.389683
9  1.207986  0.321584
8  0.091749  0.374095
0 -0.333367  0.532719
7 -0.551176  0.650956

In [87]:
unsorted_df.sort_index()

col2      col1
0 -0.333367  0.532719
1 -0.727589 -1.869765
2 -1.066839 -0.381800
3 -0.018958 -0.906805
4  0.265399 -1.052917
5  1.445366  0.389683
6 -0.674762 -0.354448
7 -0.551176  0.650956
8  0.091749  0.374095
9  1.207986  0.321584

In [93]:
unsorted_df.sort_values(by='col2')

col2      col1
2 -1.066839 -0.381800
1 -0.727589 -1.869765
6 -0.674762 -0.354448
7 -0.551176  0.650956
0 -0.333367  0.532719
3 -0.018958 -0.906805
8  0.091749  0.374095
4  0.265399 -1.052917
9  1.207986  0.321584
5  1.445366  0.389683

In [94]:
unsorted_df

col2      col1
1 -0.727589 -1.869765
4  0.265399 -1.052917
6 -0.674762 -0.354448
2 -1.066839 -0.381800
3 -0.018958 -0.906805
5  1.445366  0.389683
9  1.207986  0.321584
8  0.091749  0.374095
0 -0.333367  0.532719
7 -0.551176  0.650956

In [95]:
unsorted_df.sort_index(axis=1)

col1      col2
1 -1.869765 -0.727589
4 -1.052917  0.265399
6 -0.354448 -0.674762
2 -0.381800 -1.066839
3 -0.906805 -0.018958
5  0.389683  1.445366
9  0.321584  1.207986
8  0.374095  0.091749
0  0.532719 -0.333367
7  0.650956 -0.551176

In [96]:
df.sort_values(by='价格')

价格   折扣率
key1 key2              
格力   kt    1980.0  1.00
tcl  kt    2100.0  0.98
格力   tv    2300.0  1.00
tcl  tv    3600.0  0.96

In [97]:
df?

In [99]:
df.index

MultiIndex([( '格力', 'tv'),
            ( '格力', 'kt'),
            ('tcl', 'tv'),
            ('tcl', 'kt')],
           names=['key1', 'key2'])

In [100]:
df.index[0]

('格力', 'tv')

In [105]:
df.index.levels[0]

Index(['tcl', '格力'], dtype='object', name='key1')

In [106]:
df

价格   折扣率
key1 key2              
格力   tv    2300.0  1.00
     kt    1980.0  1.00
tcl  tv    3600.0  0.96
     kt    2100.0  0.98

In [107]:
df.sum(level=1,axis=0)

价格   折扣率
key2              
tv    5900.0  1.96
kt    4080.0  1.98

In [109]:
df.sum(level=1)

价格   折扣率
key2              
tv    5900.0  1.96
kt    4080.0  1.98

In [110]:
df

价格   折扣率
key1 key2              
格力   tv    2300.0  1.00
     kt    1980.0  1.00
tcl  tv    3600.0  0.96
     kt    2100.0  0.98

In [112]:
df.reset_index()

key1 key2      价格   折扣率
0   格力   tv  2300.0  1.00
1   格力   kt  1980.0  1.00
2  tcl   tv  3600.0  0.96
3  tcl   kt  2100.0  0.98

In [113]:
df

价格   折扣率
key1 key2              
格力   tv    2300.0  1.00
     kt    1980.0  1.00
tcl  tv    3600.0  0.96
     kt    2100.0  0.98

In [114]:
df.set_index('价格')

折扣率
价格          
2300.0  1.00
1980.0  1.00
3600.0  0.96
2100.0  0.98

In [115]:
df1 = df.reset_index()

In [116]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [117]:
df1.values

array([['格力', 'tv', 2300.0, 1.0],
       ['格力', 'kt', 1980.0, 1.0],
       ['tcl', 'tv', 3600.0, 0.96],
       ['tcl', 'kt', 2100.0, 0.98]], dtype=object)

In [118]:
df1 = DataFrame(np.arange(6).reshape(2,3), columns=['a','b','c'])

In [120]:
df2 = DataFrame(np.arange(12).reshape(3,4),columns=['a','b','c','d'])

In [121]:
df1

a  b  c
0  0  1  2
1  3  4  5

In [122]:
df2

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [123]:
df1.sub(df2)

a    b    c   d
0  0.0  0.0  0.0 NaN
1 -1.0 -1.0 -1.0 NaN
2  NaN  NaN  NaN NaN

In [124]:
df1.add(df2)

a    b     c   d
0  0.0  2.0   4.0 NaN
1  7.0  9.0  11.0 NaN
2  NaN  NaN   NaN NaN

In [125]:
df1.div(df2)

a    b         c   d
0   NaN  1.0  1.000000 NaN
1  0.75  0.8  0.833333 NaN
2   NaN  NaN       NaN NaN

In [126]:
df1.mod(df2)

a    b    c   d
0  NaN  0.0  0.0 NaN
1  3.0  4.0  5.0 NaN
2  NaN  NaN  NaN NaN

In [127]:
df

价格   折扣率
key1 key2              
格力   tv    2300.0  1.00
     kt    1980.0  1.00
tcl  tv    3600.0  0.96
     kt    2100.0  0.98

In [128]:
df.info

<bound method DataFrame.info of                价格   折扣率
key1 key2              
格力   tv    2300.0  1.00
     kt    1980.0  1.00
tcl  tv    3600.0  0.96
     kt    2100.0  0.98>

In [129]:
df.count

<bound method DataFrame.count of                价格   折扣率
key1 key2              
格力   tv    2300.0  1.00
     kt    1980.0  1.00
tcl  tv    3600.0  0.96
     kt    2100.0  0.98>

In [130]:
df1.mod(df2).count

<bound method DataFrame.count of      a    b    c   d
0  NaN  0.0  0.0 NaN
1  3.0  4.0  5.0 NaN
2  NaN  NaN  NaN NaN>

In [131]:
a = df1.mod(df2)

In [132]:
a

a    b    c   d
0  NaN  0.0  0.0 NaN
1  3.0  4.0  5.0 NaN
2  NaN  NaN  NaN NaN

In [134]:
a.count()

a    1
b    2
c    2
d    0
dtype: int64

In [136]:
a.describe()

a         b         c    d
count  1.0  2.000000  2.000000  0.0
mean   3.0  2.000000  2.500000  NaN
std    NaN  2.828427  3.535534  NaN
min    3.0  0.000000  0.000000  NaN
25%    3.0  1.000000  1.250000  NaN
50%    3.0  2.000000  2.500000  NaN
75%    3.0  3.000000  3.750000  NaN
max    3.0  4.000000  5.000000  NaN

In [139]:
se = pd.Series(['a',2,True])

In [140]:
se

0       a
1       2
2    True
dtype: object

In [141]:
se.apply(type)

0     <class 'str'>
1     <class 'int'>
2    <class 'bool'>
dtype: object

In [151]:
f = lambda x: x['item1'] + 2*x['item2']

In [152]:
f

<function __main__.<lambda>(x)>

In [153]:
2*['item2']

['item2', 'item2']

In [154]:
df = pd.DataFrame(np.arange(6).reshape(3, 2),columns = ['item1', 'item2'])

In [155]:
df

item1  item2
0      0      1
1      2      3
2      4      5

In [156]:
df['item2']

0    1
1    3
2    5
Name: item2, dtype: int64

In [157]:
df['item3'] = df.apply(f,axis=1)

In [158]:
df

item1  item2  item3
0      0      1      2
1      2      3      8
2      4      5     14

In [160]:
df['item3'] = df.apply(f,axis=1)

In [161]:
se = pd.Series([1,-1,0,1,2])

In [162]:
se.rank()

0    3.5
1    1.0
2    2.0
3    3.5
4    5.0
dtype: float64

In [163]:
se

0    1
1   -1
2    0
3    1
4    2
dtype: int64

In [164]:
se = pd.Series([1,-1,0,1,1,2])

In [165]:
se.rank()

0    4.0
1    1.0
2    2.0
3    4.0
4    4.0
5    6.0
dtype: float64

In [166]:
se.rank(method='dense')

0    3.0
1    1.0
2    2.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [167]:
df = pd.DataFrame({'x':[4,6,-1],'y':[1,0,2],'z':[5,7,-1]})

In [168]:
df

x  y  z
0  4  1  5
1  6  0  7
2 -1  2 -1

In [169]:
df.rank(axis=0)

x    y    z
0  2.0  2.0  2.0
1  3.0  1.0  3.0
2  1.0  3.0  1.0

In [170]:
df.rank(axis=1)

x    y    z
0  2.0  1.0  3.0
1  2.0  1.0  3.0
2  1.5  3.0  1.5