In [1]:
import numpy as np

In [3]:
lis = [1,2,3,4]
arr = np.array(lis)
print(arr)

[1 2 3 4]


In [4]:
np.matrix('1,2;3,4')

matrix([[1, 2],
        [3, 4]])

In [6]:
from numpy import vstack,array
from numpy.random import rand

In [8]:
data = vstack((rand(100,3) + array([.5,.5,.5]),rand(100,3)))

In [9]:
data

array([[1.21206815, 0.6554178 , 0.7881773 ],
       [0.73004012, 1.0051132 , 1.11706726],
       [1.26931919, 0.8716334 , 1.44257626],
       [1.21782345, 1.32030712, 1.35298959],
       [1.37953061, 1.26387721, 1.13967105],
       [1.01102998, 0.53085871, 1.13365988],
       [1.22847559, 1.20652137, 0.86061337],
       [0.95347343, 0.67424952, 0.80335184],
       [0.74382809, 1.48721006, 0.8899137 ],
       [1.01434315, 1.25214985, 1.42760677],
       [1.3929928 , 0.87007298, 0.66004187],
       [1.4806039 , 1.00285308, 1.44215111],
       [1.04307034, 0.94026853, 0.51239087],
       [1.33370787, 1.03074467, 0.71579686],
       [1.49709681, 1.19930019, 1.0551957 ],
       [0.88228857, 0.9089766 , 1.21063713],
       [0.6446486 , 1.33058714, 0.55125785],
       [0.87893433, 1.43063191, 1.46145597],
       [1.30511246, 0.74454979, 0.60254057],
       [1.28757562, 1.16372496, 1.35276068],
       [0.9462852 , 1.33833901, 1.24826516],
       [1.41132227, 0.51185576, 1.46803198],
       [1.

In [10]:
a = np.arange(5)*2

In [11]:
a


array([0, 2, 4, 6, 8])

In [12]:
a = np.arange(5)**2

In [13]:
a

array([ 0,  1,  4,  9, 16])

In [25]:
a = np.arange(24).reshape(2,3,4)

In [16]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
a.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
b = a
b.shape = (6,4)

In [22]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [27]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a = np.arange(9).reshape(3,3)

In [29]:
b= a*2

In [30]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [35]:
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [36]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [37]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [39]:
np.concatenate((a,b),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [40]:
oned = np.arange(2)

In [41]:
tw = oned*2

In [43]:
np.hstack((oned,tw))

array([0, 1, 0, 2])

In [44]:
c = np.arange(36).reshape(3,3,4)

In [45]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [46]:
np.dsplit(c,4)

[array([[[ 0],
         [ 4],
         [ 8]],
 
        [[12],
         [16],
         [20]],
 
        [[24],
         [28],
         [32]]]),
 array([[[ 1],
         [ 5],
         [ 9]],
 
        [[13],
         [17],
         [21]],
 
        [[25],
         [29],
         [33]]]),
 array([[[ 2],
         [ 6],
         [10]],
 
        [[14],
         [18],
         [22]],
 
        [[26],
         [30],
         [34]]]),
 array([[[ 3],
         [ 7],
         [11]],
 
        [[15],
         [19],
         [23]],
 
        [[27],
         [31],
         [35]]])]

In [49]:
d = np.arange(54).reshape(3,3,6)

In [50]:
d

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53]]])

In [51]:
np.dsplit(d,3)

[array([[[ 0,  1],
         [ 6,  7],
         [12, 13]],
 
        [[18, 19],
         [24, 25],
         [30, 31]],
 
        [[36, 37],
         [42, 43],
         [48, 49]]]),
 array([[[ 2,  3],
         [ 8,  9],
         [14, 15]],
 
        [[20, 21],
         [26, 27],
         [32, 33]],
 
        [[38, 39],
         [44, 45],
         [50, 51]]]),
 array([[[ 4,  5],
         [10, 11],
         [16, 17]],
 
        [[22, 23],
         [28, 29],
         [34, 35]],
 
        [[40, 41],
         [46, 47],
         [52, 53]]])]

In [52]:
np.split(d,3,axis=2)

[array([[[ 0,  1],
         [ 6,  7],
         [12, 13]],
 
        [[18, 19],
         [24, 25],
         [30, 31]],
 
        [[36, 37],
         [42, 43],
         [48, 49]]]),
 array([[[ 2,  3],
         [ 8,  9],
         [14, 15]],
 
        [[20, 21],
         [26, 27],
         [32, 33]],
 
        [[38, 39],
         [44, 45],
         [50, 51]]]),
 array([[[ 4,  5],
         [10, 11],
         [16, 17]],
 
        [[22, 23],
         [28, 29],
         [34, 35]],
 
        [[40, 41],
         [46, 47],
         [52, 53]]])]

In [53]:
d.ndim

3

In [55]:
d.size

54

In [56]:
d.nbytes

432

In [57]:
b = np.arange(4).reshape(2,2)

In [58]:
f = b.flat

In [59]:
f

In [66]:
[i for i in f]

[]

In [67]:
b

array([[0, 1],
       [2, 3]])

In [69]:
b.flat[2]

2

In [70]:
b

array([[0, 1],
       [2, 3]])

In [71]:
b.flat[[1,3]]

array([1, 3])

In [72]:
f

In [77]:
f[1:4]

array([1, 2, 3])

In [78]:
for item in f:
    print(item)

0
1
2
3


In [79]:
b = np.array([[1.+1.j,3.+2.j]])

In [80]:
b

array([[1.+1.j, 3.+2.j]])

In [81]:
b.astype(int)

<ipython-input-81-3edadc125634>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  b.astype(int)


array([[1, 3]])