In [1]:
import tensorflow as tf
import numpy as np

In [2]:
SEED  =23455

In [3]:
rdm = np.random.RandomState(seed = SEED)

In [4]:
x = rdm.rand(32,2)
y_ = [[x1+x2 + (rdm.rand()/10-0.05)] for (x1,x2) in x]  # 生成噪声[0,1)/10 = [0,0.1);[0,0.1)-0.05=[-0.05,0.05)
x = tf.cast(x,dtype=tf.float32)

In [5]:
w1 = tf.Variable(tf.random.normal([2,1],stddev=1,seed=1))
epoch = 15000
lr = 0.002

for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x,w1)
        loss_mse = tf.reduce_mean(tf.square(y-y_))
    grads = tape.gradient(loss_mse,w1)
    w1.assign_sub(lr*grads)
    
    if epoch%500 == 0:
        print("after %d training steps, w1 is "%(epoch))
        print(w1.numpy(),"\n")
        
print("final w1 is :",w1.numpy())

after 0 training steps, w1 is 
[[-0.8096241]
 [ 1.4855157]] 

after 500 training steps, w1 is 
[[-0.21934733]
 [ 1.6984866 ]] 

after 1000 training steps, w1 is 
[[0.0893971]
 [1.673225 ]] 

after 1500 training steps, w1 is 
[[0.28368822]
 [1.5853055 ]] 

after 2000 training steps, w1 is 
[[0.423243 ]
 [1.4906037]] 

after 2500 training steps, w1 is 
[[0.531055 ]
 [1.4053345]] 

after 3000 training steps, w1 is 
[[0.61725086]
 [1.332841  ]] 

after 3500 training steps, w1 is 
[[0.687201 ]
 [1.2725208]] 

after 4000 training steps, w1 is 
[[0.7443262]
 [1.2227542]] 

after 4500 training steps, w1 is 
[[0.7910986]
 [1.1818361]] 

after 5000 training steps, w1 is 
[[0.82943517]
 [1.1482395 ]] 

after 5500 training steps, w1 is 
[[0.860872 ]
 [1.1206709]] 

after 6000 training steps, w1 is 
[[0.88665503]
 [1.098054  ]] 

after 6500 training steps, w1 is 
[[0.90780276]
 [1.0795006 ]] 

after 7000 training steps, w1 is 
[[0.92514884]
 [1.0642821 ]] 

after 7500 training steps, w1 is 
[[0.939

In [8]:
COST = 99
PROFIT = 1
epoch = 10000
for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x,w1)
        loss_mse = tf.reduce_mean(tf.where(tf.greater(y,y_),(y-y_)*COST,(y_-y)*PROFIT))
    grads = tape.gradient(loss_mse,w1)
    w1.assign_sub(lr*grads)
    
    if epoch%500 == 0:
        print("after %d training steps, w1 is "%(epoch))
        print(w1.numpy(),"\n")
        
print("final w1 is :",w1.numpy())

after 0 training steps, w1 is 
[[1.0350155]
 [0.9322055]] 

after 500 training steps, w1 is 
[[0.93260807]
 [0.94418126]] 

after 1000 training steps, w1 is 
[[0.9360667 ]
 [0.94793314]] 

after 1500 training steps, w1 is 
[[0.9354001]
 [0.9468998]] 

after 2000 training steps, w1 is 
[[0.93473357]
 [0.9458664 ]] 

after 2500 training steps, w1 is 
[[0.934067  ]
 [0.94483304]] 

after 3000 training steps, w1 is 
[[0.93340045]
 [0.9437997 ]] 

after 3500 training steps, w1 is 
[[0.9368591 ]
 [0.94755155]] 

after 4000 training steps, w1 is 
[[0.9361925]
 [0.9465182]] 

after 4500 training steps, w1 is 
[[0.93552595]
 [0.9454848 ]] 

after 5000 training steps, w1 is 
[[0.9352799 ]
 [0.94806296]] 

after 5500 training steps, w1 is 
[[0.93461335]
 [0.9470296 ]] 

after 6000 training steps, w1 is 
[[0.9339468]
 [0.9459962]] 

after 6500 training steps, w1 is 
[[0.9369849]
 [0.9461366]] 

after 7000 training steps, w1 is 
[[0.9326137]
 [0.9439295]] 

after 7500 training steps, w1 is 
[[0.936

In [9]:
loss_ce1 = tf.losses.categorical_crossentropy([1,0],[0.6,0.4])
loss_ce2 = tf.losses.categorical_crossentropy([1,0],[0.8,0.2])

In [10]:
print(loss_ce1)
print(loss_ce2)

tf.Tensor(0.5108256, shape=(), dtype=float32)
tf.Tensor(0.22314353, shape=(), dtype=float32)


In [ ]:
with tf.GradientTape() as tape:
    h1 = tf.matmul(x_train, w1) + b1
    h1 = tf.nn.relu(h1)
    y = tf.matmul(h1,w2) + b2
    
    loss_mse = tf.reduce_mean(tf.square(y_train-y))
    
    loss_regularization = []
    loss_regularization.append(tf.nn.l2_loss(w1))
    loss_regularization.append(tf.nn.l2_loss(w2))
    loss_regularization = tf.reduce_sum(loss_regularization)
    loss = loss_mse + 0.3*loss_regularization
    
variables = [w1,b1,w2,b2]
grads = tape.gradient(loss,variables)